# Site settings
title: Multiscale Neuroanatomy Lab, INM-1, Forschungszentrum Jülich
email: casey.paquola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Multiscale Neuroanatomy Lab, INM-1, Forschungszentrum Jülich
twitter_username: CaseyPaquola
github_username: caseypaquola
search: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

